[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/api/auth/google/callback"
  to = "/.netlify/functions/auth-google-callback"
  status = 200
