// Application State Singleton
export let state = {
  lang: "en",
  theme: "system",
  todos: [],
  countdowns: [],
  googleClientToken: localStorage.getItem("google_access_token") || sessionStorage.getItem("google_access_token") || null,
  googlePersonalToken: localStorage.getItem("google_personal_token") || sessionStorage.getItem("google_personal_token") || null,
  googleWorkToken: localStorage.getItem("google_work_token") || sessionStorage.getItem("google_work_token") || null,
  googlePersonalEmail: localStorage.getItem("google_personal_email") || sessionStorage.getItem("google_personal_email") || null,
  googleWorkEmail: localStorage.getItem("google_work_email") || sessionStorage.getItem("google_work_email") || null,
  githubStatus: "disconnected",
  githubError: "",
  bitbucketStatus: "disconnected",
  bitbucketError: "",
  gitlabStatus: "disconnected",
  gitlabError: "",
  jiraStatus: "disconnected",
  jiraError: "",
  settings: {
    lang: "en",
    theme: "system",
    primaryColor: "blue",
    city: "",
    weatherUrl: "",
    worldClockTz: "",
    worldClockLabel: "",
    worldClockUrl: "",
    jiraHost: "",
    jiraEmail: "",
    jiraToken: "",
    notes: "",
    financeUrl: "",
    timerUrl: "",
    stopwatchUrl: "",
    showWeather: true,
    showWorldClock: true,
    showShortcuts: true,
    showWikipedia: true,
    wikipediaType: "news",
    storageMode: "local",
    googleClientId: "",
    githubToken: "",
    githubUsername: "",
    bitbucketWorkspace: "",
    bitbucketUsername: "",
    bitbucketToken: "",
    customEvents: [],
    oooActive: false,
    oooReturnDate: "",
    oooReturnTime: "09:00",
    hideJiraOoo: false,
    hideGithubOoo: false,
    hideBitbucketOoo: false,
    hideGitlabOoo: false,
    gitlabHost: "https://gitlab.com",
    gitlabToken: "",
    gitlabUsername: ""
  }
};
