// Application State Singleton
export let state = {
  lang: "en",
  theme: "system",
  todos: [],
  countdowns: [],
  googleClientToken: localStorage.getItem("google_access_token") || sessionStorage.getItem("google_access_token") || null,
  googlePersonalToken: localStorage.getItem("google_personal_token") || sessionStorage.getItem("google_personal_token") || null,
  googleWorkToken: localStorage.getItem("google_work_token") || sessionStorage.getItem("google_work_token") || null,
  googlePersonalEmail: localStorage.getItem("google_personal_email") || sessionStorage.getItem("google_personal_email") || null,
  googleWorkEmail: localStorage.getItem("google_work_email") || sessionStorage.getItem("google_work_email") || null,
  githubStatus: "disconnected",
  githubError: "",
  bitbucketStatus: "disconnected",
  bitbucketError: "",
  gitlabStatus: "disconnected",
  gitlabError: "",
  settings: {
    lang: "en",
    theme: "system",
    primaryColor: "blue",
    city: "",
    weatherUrl: "https://weather.com",
    worldClockTz: "",
    worldClockLabel: "",
    worldClockUrl: "https://time.is",
    notes: "",
    financeUrl: "https://www.google.com/finance/beta/quote/.INX:INDEXSP?window=1M",
    timerUrl: "https://www.google.com/search?q=countdown+timer",
    stopwatchUrl: "https://www.google.com/search?q=stopwatch",
    showWeather: true,
    showWorldClock: true,
    showWikipedia: true,
    wikipediaType: "news",
    storageMode: "local",
    googleClientId: "",
    githubToken: "",
    githubUsername: "",
    bitbucketWorkspace: "",
    bitbucketUsername: "",
    bitbucketToken: "",
    customEvents: [],
    oooActive: false,
    oooReturnDate: "",
    oooReturnTime: "09:00",
    hideJiraOoo: false,
    hideGithubOoo: false,
    hideBitbucketOoo: false,
    hideGitlabOoo: false,
    gitlabHost: "https://gitlab.com",
    gitlabToken: "",
    gitlabUsername: ""
  }
};
